### PR TITLE
r-tiledb 0.31.0

### PR DESCRIPTION
**Pull request by johnkerl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]
Wouldn't be a terrible idea to rerender the feedstock. However, it was just done about a month ago in https://github.com/conda-forge/r-tiledb-feedstock/commit/9db68aef4f2a9b2e6c42b4bae0a86efaafc3053f, so it's not required if you're in a hurry to release

**Comment by johnkerl** [comment]
@jdblischak I thought I re-rendered ... 👀

**Comment by jdblischak** [comment]
> I thought I re-rendered ...

Totally possible that no changes need to be made. I see now that you checked the box for rerendering (I forgot this was a conda-forge feedstock with the PR template)

**Comment by johnkerl** [comment]
@jdblischak nope derp sorry I had rerendered on a different branch -- not this one. Just pushed commit # 2 .....

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
This PR was submitted from a fork, but the uploads were made earlier in the internal branch [kerl/r-tiledb-0.31.0](https://github.com/conda-forge/r-tiledb-feedstock/commits/kerl/r-tiledb-0.31.0/). Specifically the [0.31.0 binaries](https://anaconda.org/conda-forge/r-tiledb/files?version=0.31.0) were uploaded from the [job](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1111618&view=results) triggered by commit https://github.com/conda-forge/r-tiledb-feedstock/commit/95eca3caa9007a1df01e1b2f3960343433c13e5a

Fortunately that commit properly reset the build number and bumped the tiledb pin to 2.27, so it is valid and we can move forward.

```sh
mamba create --dry-run -n test -c conda-forge r-tiledb=0.31.0 | grep tiledb
##  - r-tiledb=0.31.0
##  + r-tiledb                         0.31.0  r44h84d6215_0        conda-forge        2MB
##  + tiledb                           2.27.0  h6a6d8ad_1           conda-forge        4MB
```

**Comment by johnkerl** [comment]
Ah OK thank you @jdblischak 

* I made a PR branch on `conda-forge/r-tiledb-feedstock` _and never merged it_
* Then I saw the error of my ways and make a PR branch on `TileDB-Inc/r-tiledb-feedstock` _and merged it_
* Yet Conda in its wisdom published binaries from bullet # 1 above _even though I never merged that first branch_

This is highly counterintuitive for me, and an absolute danger zone -- in our nascent TileDB-R release notes (company-internal) I'll be sure to put extra / capital-letters warning to _not even push a branch_ to `conda-forge/r-tiledb-feedstock`, due to the dangerous side effects.

Thanks for teaching me!

**Comment by jdblischak** [comment]
This PR was accidentally merged into an internal branch:

image

To clean this up, I did the following (all local):

1. Pull the internal branch [conda-forge:kerl/r-tiledb-0.31.0](https://github.com/conda-forge/r-tiledb-feedstock/tree/kerl/r-tiledb-0.31.0) locally
2. Fast-forward merge into main (`git merge kerl/r-tiledb-0.31.0`)
3. Push main, now at 45fc27cacbdafb33d52ea5b240533dd22c8a70dc
4. Deleted internal branch now that it was merged into main
```sh
git branch -d kerl/r-tiledb-0.31.0
git push upstream :kerl/r-tiledb-0.31.0
```

**Pull request merged**
