### PR TITLE
Enable aarch64 and osx-arm64

### PR DESCRIPTION
**Pull request by ihnorton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ihnorton** [comment]
AFAICT there's no osx-arm64 package for base R on conda-forge yet, so this will have to wait: https://github.com/conda-forge/r-feedstock

**Comment by Shelnutt2** [comment]
> AFAICT there's no osx-arm64 package for base R on conda-forge yet, so this will have to wait: https://github.com/conda-forge/r-feedstock

I believe there is and this is just a dependency problem. I've opened PRs for the dependent packages.

https://github.com/conda-forge/r-nanotime-feedstock/pull/9
https://github.com/conda-forge/r-rcppcctz-feedstock/pull/5

**Comment by ihnorton** [comment]
I mean that I don't see an arm64 build here: https://anaconda.org/conda-forge/r
But maybe that's in progress.

**Comment by Shelnutt2** [comment]
> I mean that I don't see an arm64 build here: https://anaconda.org/conda-forge/r
> But maybe that's in progress.

I think with 4.0/4.1 they switched that package to `noarch`. The linux/win/osx arch  specific packages are on R 3.5/3.6 it looks like.

**Comment by eddelbuettel** [comment]
Maybe it had to do with ABI/API breakage?  R 3.5 imposed a rebuild requirement a rebuild, and 3.6 was compatible with it. Two years 4.0 as a new major release did the same, and 4.1 is again compatible with it.  R 4.1 is then "partially" a new one for just the M1 / aarch64 architecture.  Could that have fallen through the cracks?

**Review by eddelbuettel — COMMENTED** [review]
LGTM -- while I am not that familiar with the platform I'd say merge away

**Review by Shelnutt2 — APPROVED** [review]

**Comment by ihnorton** [comment]
Doesn't seem to have run either build that was intended.

**Comment by eddelbuettel** [comment]
Maybe it is something else?  Drilling down the build logs I get to https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=327636&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445&l=1445 which fails on

```
** testing if installed package can be loaded from temporary location
ERROR: loading failed
Error: package or namespace load failed for ‘tiledb’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '$BUILD_PREFIX/lib/R/library/00LOCK-work/00new/tiledb/libs/tiledb.dylib':
  dlopen($BUILD_PREFIX/lib/R/library/00LOCK-work/00new/tiledb/libs/tiledb.dylib, 6): no suitable image found.  Did find:
	$BUILD_PREFIX/lib/R/library/00LOCK-work/00new/tiledb/libs/tiledb.dylib: mach-o, but wrong architecture
	$BUILD_PREFIX/lib/R/library/00LOCK-work/00new/tiledb/libs/tiledb.dylib: mach-o, but wrong architecture
Error: loading failed
Execution halted
```

**Pull request merged**
